name: Run CLI test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install parquet-tools
      run: |
        python -m pip install .
    - name: Run test[help]
      run: |
        pq --help
        pq show --help
        pq csv --help
        pq inspect --help
